using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using DXP;
using EDP;
using SCH;
using PCB;

public class Commands 
{
    //Autogenerated code. Commands implementation. Begin
		//Autogenerated code. Begin of implementation [GetState_Viagrid1]
		public void GetState_Viagrid1(IServerDocumentView argContext, ref string argParameters, ref bool argEnabled, ref bool argChecked, ref bool argVisible, ref string argCaption, ref string argImageFile)
        {
            //To Do : Insert code here
        }
		//Autogenerated code. End of implementation [GetState_Viagrid1]

		//Autogenerated code. Begin of implementation [Command_Viagrid1]
		public void Command_Viagrid1(IServerDocumentView view, ref string parameters)
        {
            //To Do : Insert code here
        }
		//Autogenerated code. End of implementation [Command_Viagrid1]

		//Autogenerated code. Begin of implementation [GetState_Viagrid]
		public void GetState_Viagrid(IServerDocumentView argContext, ref string argParameters, ref bool argEnabled, ref bool argChecked, ref bool argVisible, ref string argCaption, ref string argImageFile)
        {
            argVisible = true;
            argEnabled = true;
        }
		//Autogenerated code. End of implementation [GetState_Viagrid]

		//Autogenerated code. Begin of implementation [Command_Viagrid]
		public void Command_Viagrid(IServerDocumentView view, ref string parameters)
        {
            IPCB_ServerInterface pcbServer = PCB.GlobalVars.PCBServer;
            if (pcbServer == null) return;

            IPCB_Board pcbBoard = pcbServer.GetCurrentPCBBoard();
            if (pcbBoard == null) return;

            DXP.Utils.RunCommand("PCB:DeSelect", "Scope=All");

            var boundingRect = pcbBoard.GetState_BoardOutline().BoundingRectangle();
            var gridSize = (int)pcbBoard.GetState_ComponentGridSize();
            var delta = EDP.Utils.MMsToCoord(0.001);

            IPCB_BoardIterator iterator = pcbBoard.BoardIterator_Create();
            iterator.AddFilter_ObjectSet(new PCB.TObjectSet(PCB.TObjectId.eViaObject));
            iterator.AddFilter_LayerSet(PCBConstant.V6AllLayersSet);
            iterator.AddFilter_Area(boundingRect.Left, boundingRect.Bottom, boundingRect.Right, boundingRect.Top);

            IPCB_Primitive pcbObject = iterator.FirstPCBObject();
            while (pcbObject != null)
            {
               if (pcbObject is IPCB_Via via
                   && (via.GetState_XLocation() % gridSize > delta
                       || via.GetState_XLocation() % gridSize > delta))
                   via.SetState_Selected(true);
               pcbObject = iterator.NextPCBObject();
            }

            pcbBoard.BoardIterator_Destroy(ref iterator);

            DXP.Utils.RunCommand("PCB:RunQuery", "Apply=True|Expr=IsSelected|Mask=True|Select=True");
        }
		//Autogenerated code. End of implementation [Command_Viagrid]

    //Autogenerated code. Commands implementation. End
}

