using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using DXP;
using EDP;

namespace CSharpPlugin
{
    public interface IPluginFactory
    {
        object InvokePluginFactory(IClient a);
    }

    [ClassInterface(ClassInterfaceType.None)]
    public class PluginFactory : IPluginFactory
    {
        public object InvokePluginFactory(IClient a)
        {
            PluginServerModule serverModule = new PluginServerModule(a, "Viagrid");
            return serverModule;
        }
    }

    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    public class PluginServerModule : ServerModule
    {
        public PluginServerModule(IClient argClient, string argModuleName)
            : base(argClient, argModuleName)
        {
        }

        protected override void InitializeCommands()
        {
            //Autogenerated code. Commands registration. Begin
		((CommandLauncher)CommandLauncher).RegisterCommand("Viagrid", this.Command_Viagrid, this.GetState_Viagrid);
            //Autogenerated code. Commands registration. End
        }

        protected override IServerDocument NewDocumentInstance(string kind, string fileName)
        {
            return null;
        }

       //Autogenerated code. Commands definition. Begin
		//Autogenerated code. Begin of definition [GetState_Viagrid]
		private void GetState_Viagrid(IServerDocumentView argContext, ref string argParameters, ref bool argEnabled, ref bool argChecked, ref bool argVisible, ref string argCaption, ref string argImageFile)
        {
            new Commands().GetState_Viagrid(argContext, ref argParameters, ref argEnabled, ref argChecked, ref argVisible, ref argCaption, ref argImageFile);
            return;
        }
		//Autogenerated code. End of definition [GetState_Viagrid]

		//Autogenerated code. Begin of definition [Command_Viagrid]
		private void Command_Viagrid(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_Viagrid(argView, ref argParameters);
            return;
        }
		//Autogenerated code. End of definition [Command_Viagrid]

       //Autogenerated code. Commands definition. End
    }
}
